// Automatically generated by build_web/build.py, do not edit
#ifndef MPU6050_VIEW_INDEX_H
#define MPU6050_VIEW_INDEX_H

#include <Arduino.h>

const char* const webSrc[] = {
        "/index.html",
        "/vite.svg",
        "/assets/index-Be8Fl4oq.js",
        "/assets/index-CMDX60TJ.css",
        "/model/plane.obj"
};
#endif // MPU6050_VIEW_INDEX_H